# -*- coding: utf-8 -*-
"""Shell script şablonları - Ana modül. Alt modülleri toplar."""

from templates_tvplus import (
    TVPLUS_SETUP_TEMPLATE,
    TVPLUS_UNINSTALL_TEMPLATE,
)
from templates_dns import (
    DNS_CHAIN_SETUP_TEMPLATE,
    DNS_CHAIN_UNINSTALL_TEMPLATE,
)
from templates_zapret import (
    ZAPRET_SETUP_TEMPLATE,
    ZAPRET_UNINSTALL_TEMPLATE,
)
from templates_tailscale import (
    TAILSCALE_SETUP_TEMPLATE,
    TAILSCALE_UNINSTALL_TEMPLATE,
)
from templates_wan import (
    WAN_SETUP_TEMPLATE,
    WAN_UNINSTALL_TEMPLATE,
)
from templates_ipv6 import (
    IPV6_DISABLE_TEMPLATE,
    IPV6_ENABLE_TEMPLATE,
)
from templates_disk import (
    DISK_EXPAND_TEMPLATE,
    DISK_STATUS_TEMPLATE,
    ARGON_FAN_TEMPLATE,
    ARGON_FAN_UNINSTALL_TEMPLATE,
)

__all__ = [
    "TVPLUS_SETUP_TEMPLATE", "TVPLUS_UNINSTALL_TEMPLATE",
    "DNS_CHAIN_SETUP_TEMPLATE", "DNS_CHAIN_UNINSTALL_TEMPLATE",
    "ZAPRET_SETUP_TEMPLATE", "ZAPRET_UNINSTALL_TEMPLATE",
    "TAILSCALE_SETUP_TEMPLATE", "TAILSCALE_UNINSTALL_TEMPLATE",
    "WAN_SETUP_TEMPLATE", "WAN_UNINSTALL_TEMPLATE",
    "IPV6_DISABLE_TEMPLATE", "IPV6_ENABLE_TEMPLATE",
    "DISK_EXPAND_TEMPLATE", "DISK_STATUS_TEMPLATE",
    "ARGON_FAN_TEMPLATE", "ARGON_FAN_UNINSTALL_TEMPLATE",
]